=== HearthstoneSimulator/SimulatorTest/Hearthstone/bin/Debug/XMLCardBase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="Cards">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Card" type="CardT" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="CardT">
		<xs:sequence>
			<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Attack" type="xs:integer" default="0" minOccurs="1" maxOccurs="1"/>
			<xs:element name="HP" type="xs:integer" default="0" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Manacost" type="xs:integer" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Tags" type="TagsT" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Skills" type="SkillsT" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TagsT">
		<xs:sequence>
			<xs:element name="Minion" minOccurs="0"/>
			<xs:element name="Spell" minOccurs="0"/>
			<!--List of Minion Types-->
			<xs:element name="Murloc" minOccurs="0"/>
			<xs:element name="Beast" minOccurs="0"/>
			<xs:element name="Demon" minOccurs="0"/>
			<xs:element name="Totem" minOccurs="0"/>
			<xs:element name="Mech" minOccurs="0"/>
			<!--List of minion basic abbilities-->
			<xs:element name="Taunt" minOccurs="0"/>
			<xs:element name="Charge" minOccurs="0"/>
			<xs:element name="Spell_Damage" type="xs:integer" default="1" minOccurs="0"/>
			<!--List of tags responsible for subset selection-->
			<xs:element name="All" minOccurs="0"/>
			<xs:element name="Other" minOccurs="0"/>
			<xs:element name="Enemy" minOccurs="0"/>
			<xs:element name="Own" minOccurs="0"/>
			<xs:element name="Player" minOccurs="0"/>
			<xs:element name="Random" minOccurs="0"/>
			<xs:element name="Any" minOccurs="0"/>
			<xs:element name="Self" minOccurs="0"/>
			<xs:element name="You" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SkillsT">
		<xs:sequence>
			<xs:element name="Skill" type="SkillT" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EffectT">
		<xs:sequence>
			<xs:element name="Function">
				<xs:complexType mixed="true">
					<xs:attribute name="Attack" type="xs:string"/>
					<xs:attribute name="AttackModificationType">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="ADDITION"/>
								<xs:enumeration value="SUBSTRACTION"/>
								<xs:enumeration value="SET"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="Defense" type="xs:string"/>
					<xs:attribute name="DefenseModificationType">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="ADDITION"/>
								<xs:enumeration value="SUBSTRACTION"/>
								<xs:enumeration value="SET"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="targets" type="xs:integer"/>
					<xs:attribute name="value" type="xs:integer"/>
					<xs:attribute name="selector">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="PLAYER"/>
								<xs:enumeration value="RANDOM"/>
								<xs:enumeration value="ALL"/>
								<xs:enumeration value="AUTO"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="summonedCreatureName" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TypeOfSkillT"/>
	<xs:complexType name="SkillT">
		<xs:sequence>
			<xs:element name="Type"/>
			<xs:element name="Trigger" minOccurs="0"/>
			<xs:element name="Target">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Tags" type="TagsT"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Effect" type="EffectT"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== HearthstoneSimulator/SimulatorTest/Hearthstone/XMLCardBase.xml
<?xml version="1.0" encoding="utf-8"?>
<Cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:/Users/Marin/Documents/Visual Studio 2013/Projects/Hearthstone/XMLCardBase.xsd">
  <Card>
    <Name>Chillwind Yeti</Name>
    <Attack>4</Attack>
    <HP>5</HP>
    <Manacost>4</Manacost>
    <Tags>
      <Minion/>
    </Tags>
  </Card>
  <Card>
    
    <Name>Elven Archer</Name>
    <Attack>1</Attack>
    <HP>1</HP>
    <Manacost>1</Manacost>
    <Tags>
      <Minion/>
    </Tags>
    <Skills>
      <Skill>
        <Type>Battlecry</Type>
        <Target>
          <Tags>
            <!--nothing means any... this specifies the set of possible targets-->
          </Tags>
        </Target>
        <Effect>
          <Function targets="1" value="1" selector="PLAYER">Deal_Damage</Function>
        </Effect>
      </Skill>
      <!--
      <Skill>
        <Type>battlecry/deathrattle/inspire/aura/buff/triggered_action</Type> mby as a tag??
        <Target>
          <Tags>
            <Monster/>
            <Attack value="5" precision="GT"/>
            <Enemy/>
            <Demon/>
            This should select only targets that are enemy monsters that are demons with attack of 6 or more
          </Tags>
          <Trigger>
            should be any of the possible events -> damage done, monster summoned,... 
          </Trigger>
        </Target>
        <Effect>
          <Function>Deal_Damage/Return_to_Hand/destroy/place_buff/discard/summon/transform/draw_cards</Function>
          
        </Effect>
      </Skill>
      <Battlecry>
        <Effect>
          <Kind>Damage_dealing</Kind>
          <Target>CHARACTER</Target>
          <Targets>1</Targets>
          <Selection>PLAYER</Selection>
          <Ammount>1</Ammount>
        </Effect>
      </Battlecry>
      -->
    </Skills>
  </Card>
  <Card>
    <Name>Goldshire Footman</Name>
    <Attack>1</Attack>
    <HP>2</HP>
    <Manacost>1</Manacost>
    <Tags>
      <Minion/>
      <Taunt/>
    </Tags>
  </Card>
  <Card>
    <Name>Grimscale Oracle</Name>
    <Attack>1</Attack>
    <HP>1</HP>
    <Manacost>1</Manacost>
    <Tags>
      <Minion/>
      <Murloc/>
    </Tags>
    <!--
    <Type>Murloc</Type>
    -->
    <!--
    <Skills>
      <Aura>
        <Effect>
          <Kind>Buff</Kind>
          <Target></Target>
        </Effect>
      </Aura>
    </Skills>
    -->
  </Card>
  <Card>
    <Name>Murloc Raider</Name>
    <Attack>2</Attack>
    <HP>1</HP>
    <Manacost>1</Manacost>
    <Tags>
      <Minion/>
      <Murloc/>
    </Tags>
    <!--
    <Type>Murloc</Type>
    -->
  </Card>
  <Card>
    <Name>Stonetusk Boar</Name>
    <Attack>1</Attack>
    <HP>1</HP>
    <Manacost>1</Manacost>
    <Type>Beast</Type>
    <Skills>
      <Charge/>
    </Skills>
  </Card>
  <Card>
    <Name>Voodoo Doctor</Name>
    <Attack>2</Attack>
    <HP>1</HP>
    <Manacost>1</Manacost>
    <Skills>
      <Battlecry>
        <Effect>
          <Kind>Heal</Kind>
          <Target>CHARACTER</Target>
          <Targets>1</Targets>
          <Selection>Player</Selection>
          <Ammount>2</Ammount>
        </Effect>
      </Battlecry>
    </Skills>
  </Card>
  <Card>
    <Name>Acidic Swamp Ooze</Name>
    <Attack>3</Attack>
    <HP>2</HP>
    <Manacost>2</Manacost>
    <Skills>
      <Battlecry>
        <Effect>
          <Kind>Destroy_Enemy_Weapon</Kind>
        </Effect>
      </Battlecry>
    </Skills>
  </Card>
  <Card>
    <Name>Bloodfen Raptor</Name>
    <Attack>3</Attack>
    <HP>2</HP>
    <Manacost>2</Manacost>
    <Type>Beast</Type>
  </Card>
  <Card>
    <Name>Bluegill Warrior</Name>
    <Attack>2</Attack>
    <HP>1</HP>
    <Manacost>2</Manacost>
    <Type>Murloc</Type>
    <Skills>
      <Charge/>
    </Skills>
  </Card>
  <Card>
    <Name>Frostwolf Grunt</Name>
    <Attack>2</Attack>
    <HP>2</HP>
    <Manacost>2</Manacost>
    <Skills>
      <Taunt/>
    </Skills>
  </Card>
  <Card>
    <Name>Kobold Geomancer</Name>
    <Attack>2</Attack>
    <HP>2</HP>
    <Manacost>2</Manacost>
    <Skills>
      <Spelldamage>1</Spelldamage>
    </Skills>
  </Card>
  <Card>
    <Name>Murloc Tidehunter</Name>
    <Attack>2</Attack>
    <HP>1</HP>
    <Manacost>2</Manacost>
    <Type>Murloc</Type>
    <Skills>
      <Battlecry>
        <Effect>
          <Kind>Summon</Kind>
          <Target>Murloc scout</Target>
          <Ammount>1</Ammount>
          <Side>PLAYER</Side>
        </Effect>
      </Battlecry>
    </Skills>
  </Card>
  <Card>
    <Name>Novice Engineer</Name>
    <Attack>1</Attack>
    <HP>1</HP>
    <Manacost>2</Manacost>
    <Skills>
      <Battlecry>
        <Effect>
          <Kind>Card_Draw</Kind>
          <Target>PLAYER</Target>
          <Ammount>1</Ammount>
        </Effect>
      </Battlecry>
    </Skills>
  </Card>
  <Card>
    <Name>River Crocolisk</Name>
    <Attack>2</Attack>
    <HP>3</HP>
    <Manacost>2</Manacost>
    <Tags>
      <Minion/>
    </Tags>
  </Card>
  <Card>
    <Name>Dalaran Mage</Name>
    <Attack>1</Attack>
    <HP>4</HP>
    <Manacost>3</Manacost>
    <Tags>
      <Minion/>
      <Spell_Damage value="1"/>
    </Tags>
  </Card>
  <Card>
    <Name>Ironforge Rifleman</Name>
    <Attack>2</Attack>
    <HP>2</HP>
    <Manacost>3</Manacost>
    <Tags>
      <Minion/>
    </Tags>
    <Skills>
      <Battlecry>
        <Effect>
          <Kind>Damage_dealing</Kind>
          <Target>ANY</Target>
          <Ammount>1</Ammount>
          <!--TODO-->
        </Effect>
      </Battlecry>
    </Skills>
  </Card>
  <Card>
    <Name>Ironfur Grizzly</Name>
    <Attack>3</Attack>
    <HP>3</HP>
    <Manacost>3</Manacost>
    <Tags>
      <Minion/>
      <Taunt/>
    </Tags>
  </Card>
  <Card>
    <Name>Magma Rager</Name>
    <Attack>5</Attack>
    <HP>1</HP>
    <Manacost>3</Manacost>
    <Tags>
      <Minion/>
    </Tags>
  </Card>
  <Card>
    <Name>Raid Leader</Name>
    <Attack>2</Attack>
    <HP>2</HP>
    <Manacost>3</Manacost>
    <Tags>
      
    </Tags>
    <Skills>
      <!--TODO-->
    </Skills>
  </Card>
  <Card>
    <Name>Razorfen Hunter</Name>
    <Attack>2</Attack>
    <HP>3</HP>
    <Manacost>3</Manacost>
    <Tags>
      <Minion/>
    </Tags>
    <Skills>
      <Battlecry>
<!--TODO-->
      </Battlecry>
    </Skills>
  </Card>
  <Card>
    <Name>Silverback Patriarch</Name>
    <Attack>1</Attack>
    <HP>4</HP>
    <Manacost>3</Manacost>
    <Tags>
      <Minion/>
      <Taunt/>
      <Beast/>
    </Tags>
  </Card>
  <Card>
    <Name>Wolfrider</Name>
    <Attack>3</Attack>
    <HP>1</HP>
    <Manacost>3</Manacost>
    <Tags>
      <Minion/>
    </Tags>
  </Card>
  <Card>
    <Name>Chilwind Yeti</Name>
    <Attack>4</Attack>
    <HP>5</HP>
    <Manacost>4</Manacost>
    <Tags>
      <Minion/>
    </Tags>
  </Card>
    <Card>
      <Name>Dragonling Mechanic</Name>
      <Attack>2</Attack>
      <HP>4</HP>
      <Manacost>4</Manacost>
      <Tags>
        <Minion/>
      </Tags>
      <!--TODO-->
    </Card>
    <Card>
      <Name>Gnomish Inventor</Name>
      <Attack>2</Attack>
      <HP>4</HP>
      <Manacost>4</Manacost>
      <Tags>
        <Minion/>
      </Tags>
      <!--TODO-->
    </Card>
    <Card>
      <Name>Oasis Snapjaw</Name>
      <Attack>2</Attack>
      <HP>7</HP>
      <Manacost>4</Manacost>
      <Tags>
        <Minion/>
      </Tags>
    </Card>
    <Card>
      <Name>Ogre Magi</Name>
      <Attack>4</Attack>
      <HP>4</HP>
      <Manacost>4</Manacost>
      <Tags>
        <Spell_Damage value="1"/>
        <Minion/>
      </Tags>
    </Card>
    <Card>
      <Name>Sanjin Shieldmasta</Name>
      <Attack>3</Attack>
      <HP>5</HP>
      <Manacost>4</Manacost>
      <Tags>
        <Taunt/>
        <Minion/>
      </Tags>
    </Card>
  <Card>
    <Name>Stormwind Knight</Name>
    <Attack>2</Attack>
    <HP>5</HP>
    <Manacost>4</Manacost>
    <Tags>
      <Minion/>
      <Charge/>
    </Tags>
  </Card>
  <Card>
    <Name>Booty Bay Bodyguard</Name>
    <Attack>5</Attack>
    <HP>4</HP>
    <Manacost>5</Manacost>
    <Tags>
      <Taunt/>
      <Minion/>
    </Tags>
  </Card>
  <Card>
    <Name>Darkscale Healer</Name>
    <Attack>4</Attack>
    <HP>5</HP>
    <Manacost>5</Manacost>
    <Tags>
      <Minion/>
    </Tags>
    <!--TODO-->
  </Card>
  <Card>
    <Name>Frowstwolf Warlord</Name>
    <Attack>4</Attack>
    <HP>4</HP>
    <Manacost>5</Manacost>
    <Tags>
      <Minion/>
    </Tags>
    <!--TODO-->
  </Card>
  <Card>
    <Name>Garubashi Berseker</Name>
    <Attack>2</Attack>
    <HP>7</HP>
    <Manacost>5</Manacost>
    <Tags>
      <Minion/>
    </Tags>
    <!--TODO-->
  </Card>
  <Card>
    <Name>Nightblade</Name>
    <Attack>4</Attack>
    <HP>4</HP>
    <Manacost>5</Manacost>
    <Tags>
      <Minion/>
    </Tags>
    <!--TODO-->
  </Card>
  <Card>
    <Name>Stormspike Commando</Name>
    <Attack>2</Attack>
    <HP>4</HP>
    <Manacost>5</Manacost>
    <Tags>
      <Minion/>
    </Tags>
    <!--TODO-->
  </Card>
  <Card>
    <Name>Archmage</Name>
    <Attack>4</Attack>
    <HP>7</HP>
    <Manacost>6</Manacost>
    <Tags>
      <Spell_Damage value="1"/>
      <Minion/>
    </Tags>
  </Card>
  <Card>
    <Name>Boulderfist Ogre</Name>
    <Attack>6</Attack>
    <HP>7</HP>
    <Manacost>6</Manacost>
    <Tags>
      <Minion/>
    </Tags>
  </Card>
  <Card>
    <Name>Reckless Rocketeer</Name>
    <Attack>5</Attack>
    <HP>2</HP>
    <Manacost>6</Manacost>
    <Tags>
      <Charge/>
      <Minion/>
    </Tags>
  </Card>
  <Card>
    <Name>Core Hound</Name>
    <Attack>9</Attack>
    <HP>5</HP>
    <Manacost>7</Manacost>
    <Tags>
      <Minion/>
    </Tags>
  </Card>
  <Card>
    <Name>Stormwind Champion</Name>
    <Attack>6</Attack>
    <HP>6</HP>
    <Manacost>7</Manacost>
    <Tags>
      <Minion/>
    </Tags>
    <!--TODO-->
  </Card>
  <Card>
    <Name>War Golem</Name>
    <Attack>7</Attack>
    <HP>7</HP>
    <Manacost>7</Manacost>
    <Tags>
      <Minion/>
    </Tags>
  </Card>
</Cards>

=== HearthstoneSimulator/SimulatorTest/Hearthstone/zaloha/XMLCardBase.xml
<?xml version="1.0" encoding="utf-8"?>
<Cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:/Users/Marin/Documents/Visual Studio 2013/Projects/Hearthstone/XMLCardBase.xsd">
  <Card>
    <Name>Chillwind Yeti</Name>
    <Attack>4</Attack>
    <HP>5</HP>
    <Manacost>4</Manacost>
  </Card>
  <Card>
    <Name>Elven Archer</Name>
    <Attack>1</Attack>
    <HP>1</HP>
    <Manacost>1</Manacost>
    <Skills>
      <Battlecry>
        <Effect>
          <Kind>Damage_dealing</Kind>
          <Target>CHARACTER</Target>
          <Targets>1</Targets>
          <Selection>PLAYER</Selection>
          <Ammount>1</Ammount>
        </Effect>
      </Battlecry>
    </Skills>
  </Card>
  <Card>
    <Name>Goldshire Footman</Name>
    <Attack>1</Attack>
    <HP>2</HP>
    <Manacost>1</Manacost>
    <Skills>
      <Taunt/>
    </Skills>
  </Card>
  <Card>
    <Name>Grimscale Oracle</Name>
    <Attack>1</Attack>
    <HP>1</HP>
    <Manacost>1</Manacost>
    <Type>Murloc</Type>
    <Skills>
      <Aura>
        <Effect>
          <Kind>Buff</Kind>
          <Target></Target>
        </Effect>
      </Aura>
    </Skills>
  </Card>
  <Card>
    <Name>Murloc Raider</Name>
    <Attack>2</Attack>
    <HP>1</HP>
    <Manacost>1</Manacost>
    <Type>Murloc</Type>
  </Card>
  <Card>
    <Name>Stonetusk Boar</Name>
    <Attack>1</Attack>
    <HP>1</HP>
    <Manacost>1</Manacost>
    <Type>Beast</Type>
    <Skills>
      <Charge/>
    </Skills>
  </Card>
  <Card>
    <Name>Voodoo Doctor</Name>
    <Attack>2</Attack>
    <HP>1</HP>
    <Manacost>1</Manacost>
    <Skills>
      <Battlecry>
        <Effect>
          <Kind>Heal</Kind>
          <Target>CHARACTER</Target>
          <Targets>1</Targets>
          <Selection>Player</Selection>
          <Ammount>2</Ammount>
        </Effect>
      </Battlecry>
    </Skills>
  </Card>
  <Card>
    <Name>Acidic Swamp Ooze</Name>
    <Attack>3</Attack>
    <HP>2</HP>
    <Manacost>2</Manacost>
    <Skills>
      <Battlecry>
        <Effect>
          <Kind>Destroy_Enemy_Weapon</Kind>
        </Effect>
      </Battlecry>
    </Skills>
  </Card>
  <Card>
    <Name>Bloodfen Raptor</Name>
    <Attack>3</Attack>
    <HP>2</HP>
    <Manacost>2</Manacost>
    <Type>Beast</Type>
  </Card>
  <Card>
    <Name>Bluegill Warrior</Name>
    <Attack>2</Attack>
    <HP>1</HP>
    <Manacost>2</Manacost>
    <Type>Murloc</Type>
    <Skills>
      <Charge/>
    </Skills>
  </Card>
  <Card>
    <Name>Frostwolf Grunt</Name>
    <Attack>2</Attack>
    <HP>2</HP>
    <Manacost>2</Manacost>
    <Skills>
      <Taunt/>
    </Skills>
  </Card>
  <Card>
    <Name>Kobold Geomancer</Name>
    <Attack>2</Attack>
    <HP>2</HP>
    <Manacost>2</Manacost>
    <Skills>
      <Spelldamage>1</Spelldamage>
    </Skills>
  </Card>
  <Card>
    <Name>Murloc Tidehunter</Name>
    <Attack>2</Attack>
    <HP>1</HP>
    <Manacost>2</Manacost>
    <Type>Murloc</Type>
    <Skills>
      <Battlecry>
        <Effect>
          <Kind>Summon</Kind>
          <Target>Murloc scout</Target>
          <Ammount>1</Ammount>
          <Side>PLAYER</Side>
        </Effect>
      </Battlecry>
    </Skills>
  </Card>
  <Card>
    <Name>Novice Engineer</Name>
    <Attack>1</Attack>
    <HP>1</HP>
    <Manacost>2</Manacost>
    <Skills>
      <Battlecry>
        <Effect>
          <Kind>Card_Draw</Kind>
          <Target>PLAYER</Target>
          <Ammount>1</Ammount>
        </Effect>
      </Battlecry>
    </Skills>
  </Card>
</Cards>
